version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    container_name: habit-tracker-db
    restart: always
    environment:
      POSTGRES_DB: habittracker
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
