import type { Metadata } from "next";
import { Urbanist } from "next/font/google";
import "./globals.css";
import { MobileNavbar } from "@/components/mobile-navbar";

const urbanist = Urbanist({
  variable: "--font-urbanist",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${urbanist.variable} antialiased min-h-screen pb-14`}>
        {children}
        <MobileNavbar />
      </body>
    </html>
  );
}
